### ISSUE TITLE
Adding attribute to <html> tag

### ISSUE THREAD

**Issue by TueNguyen2911** [Hargne/html-creator#14]
Hi, I was trying to add a `lang` attribute to `html` , however, there is no method in class `Document` that allow me to get `<html>` element or adding attribute to it. 

I ended up getting the HTML string using `getHTML()` and edit using regEx. 

Is it possible to add some code to `getHTML()` to make it easier?

For example: 
```javascript 
getHTML(lang) {
		if(lang)
			return `<!DOCTYPE html><html lang=${lang}>${this.getContentInHTML()}</html>`;
		return `<!DOCTYPE html><html>${this.getContentInHTML()}</html>`;
	}
```

**Comment by Hargne** [comment]
Hi, 
Sounds like a neat idea. I will see if I can add functionality to modify the html-tag. 👍
