### ISSUE TITLE
Main folder missing after install

### ISSUE THREAD

**Issue by giriannamalai** [Hargne/html-creator#24]
Error: Cannot find module '/var/www/html/proj/node_modules/html-creator/dist/main'. Please verify that the package.json has a valid "main" entry
The main entry **"main": "dist/main",**
But the dist folder does not contain main folder. 

Fix: Created dist/main folder and moved the index.js in it.

Node: v14.17.5

**Comment by trapcodeio** [comment]
Had to write a code for this. Please fix.

```javascript
const fs = require('fs');
const pathToPackageDotJson = require.resolve('html-creator/package.json');
const packageDotJson = require(pathToPackageDotJson);

packageDotJson.main = "dist/index.js";
packageDotJson.unpkg = "dist/index.js";

fs.writeFileSync(pathToPackageDotJson, JSON.stringify(packageDotJson, null, 2));
```
