### ISSUE TITLE
Compressed result as previous version 0.4.4

### ISSUE THREAD

**Issue by trapcodeio** [Hargne/html-creator#26]
First, I would like to say: Thank you for this awesome library. 😁 

After upgrading from `0.4.4` to `0.6.1` i noticed the rendered result has changed.
The old version renders a more compressed HTML than the new.
Is there an option to return compressed results? 

These are links to runkit tests...

NEW: [https://runkit.com/embed/ihmlwatb26ta](https://runkit.com/embed/ihmlwatb26ta)
OLD: [https://runkit.com/embed/0lti2qtil2vb](https://runkit.com/embed/0lti2qtil2vb)

Images of results

###### NEW:
<img width="547" alt="Screenshot 2021-11-13 at 8 32 32 PM" src="https://user-images.githubusercontent.com/48396844/141656751-6d85a682-69df-4e35-a3d9-693a2152bfff.png">

###### OLD:
<img width="798" alt="Screenshot 2021-11-13 at 8 33 24 PM" src="https://user-images.githubusercontent.com/48396844/141656776-11396a5d-e067-412e-8e17-f93401e34394.png">

**Comment by Hargne** [comment]
Hi,
Yes, as of 0.6.0 the package formats the HTML using the Prettier standard.
There are currently no option to disable the formatting, however I suppose it should be possible to add one.

**Comment by trapcodeio** [comment]
Okay, Should I be expecting any update or fix soon?
If you are busy I could assist by creating a pull request for it.
