### ISSUE TITLE
Error: Cannot find module 'prettier'

### ISSUE THREAD

**Issue by GoudronViande24** [Hargne/html-creator#29]
Hi, when I start my program, at soon as it requires html-creator it crashes with this error:

```
Error: Cannot find module 'prettier'
```

I installed html-creator with `npm i html-creator` .
I tried installing prettier manually with `npm i prettier`, and now my program works.
Maybe add it to `package.json` so we don't have to manage it manually?

Node.js v16.13.1
html-creator v0.6.2
Windows 10 latest version, Powershell

**Comment by GoudronViande24** [comment]
I looked at the package.json and found that it is required as dev dependency. If it's moved to normal dependencies, it should work I think? I may be forgetting about something though. 
I made a PR with the change: #30

**Comment by YMA-MDL** [comment]
@GoudronViande24 Did you, by any chance, published your fork on npm ?

**Comment by GoudronViande24** [comment]
No, but if it may help anyone I could do it
Otherwise if you need to install it in your project, the package.json also suppports git repos I believe

**Comment by Hargne** [comment]
Hi,

Sorry for the late reply!
It is correct that Prettier should be a dependency (and not a dev dependency). I have merged the PR and will publish a new release

**Comment by YMA-MDL** [comment]
Very cool for coming back :)
👍🏽 
Thank you
