### ISSUE TITLE
Remove tags before render

### ISSUE THREAD

**Issue by danilopaulinodasilva** [Hargne/html-creator#3]
Hi there, awesome module! Thanks for that :)

I was wondering if is there a way to not output `<!DOCTYPE html><html> ... </html>` tags when use `html.renderHTML()`.

I just want to output the tags I chose, like `<div>`, `<p>`, `<span>`...

Thanks! 👍

**Comment by Hargne** [comment]
Hi (and thanks 🎉)
I don’t believe that feature exists right now, but I think it is a fair request. I will try to implement such a feature asap!

**Comment by rjvim** [comment]
Would like this feature

**Comment by Hargne** [comment]
As mentioned above, it was released in [v0.4.4](https://github.com/Hargne/html-creator/releases/tag/0.4.4)
