### ISSUE TITLE
Execute script tag

### ISSUE THREAD

**Issue by danilopaulinodasilva** [Hargne/html-creator#6]
Hi there, I have the following scenario:

```
const script = `
        localStorage.setItem("foo", "bar");
        window.alert("foo");
`;

```

```
{
        type: 'script',
        content: script
}
```

I can see it rendered in HTML, but the content of <script> created not execute. Is this normal or I am missing something here?

Thanks!

**Comment by Hargne** [comment]
Hi,
I haven't had the intention to add script before - but I did some quick testing and it seems to be working over here.

Here is the code I used:

```js
const html = new htmlCreator([
  {
    type: "head",
    content: [
      {
        type: "title",
        content: "Generated HTML"
      },
      {
        type: "script",
        content: `
		console.log("bar");
		window.alert("foo");
	`
      }
    ]
  },
  {
    type: "body",
    attributes: {
      style: "padding: 1rem"
    },
    content: [
      {
        type: "div",
        content: [
          {
            type: "span",
            attributes: {
              class: "button",
              style: `padding: 5px;background-color: #eee;					`
            },
            content: "A Button Span Deluxe"
          }
        ]
      }
    ]
  }
]);
```

Please have a go by using a similar setup and get back to be if it still is not working!

**Comment by danilopaulinodasilva** [comment]
First, thanks for the quick reply! Your code works just fine.

But maybe my case is beyond this here. Because I'm generating the HTML inside my NodeJS API. 

So I made a .js file what do a XHR call to my NodeJS API and when receive the response it render the HTML content next to the script who made the XHR call.

So is kinda that:

```
<html>
<head></head>
<body>

<script src="myxhr.js"></script>

</body>
</html>
```

And the result is:

```
<html>
<head></head>
<body>

<div><span class="button">A Button Span Deluxe</span></div>
<script src="myxhr.js"></script>

</body>
</html>
```

So the HTML is already formed and I just nest the elements next to my script, where I can't create another ```<head>``` element. So if the ```<script>``` rendered by ```html-creator``` depends to inject inside ```<head>``` I think I need find another way to do it.

:/

**Comment by Hargne** [comment]
It should work the same if you injected the script within the content of another element like so:

```js
{
        type: "div",
        content: [
          {
            type: "span",
            attributes: {
              class: "button",
              style: `padding: 5px;background-color: #eee;`
            },
            content: "A Button Span Deluxe"
	  },
          {
            type: "script",
            content: `console.log("foo");`
          }
        ]
},
```

**Comment by Hargne** [comment]
I am closing this for now. Please open it again if it is still relevant
